name: bicep-deployment

on:
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: "bicep-deployment-rg"

permissions:
  id-token: write
  contents: read

jobs:
  basic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Azure CLI
        uses: azure/cli@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account list --output table

      - name: Install Bicep CLI
        run: |
          az bicep install

      ## deploy bicetp file with parameter file
      # - name: Deploy Bicep Template
      #   run: |
      #     az deployment group create \
      #       --resource-group $AZURE_RESOURCE_GROUP \
      #       --template-file main.bicep \
      #       --parameters @main.parameters.json
