name: Deploy Bicep to Azure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Install Bicep CLI
        run: |
          az bicep install

      - name: check az cli version
        run: |
          az --version

      - name: deploy bicep file using az cli
        run: |
          az deployment group create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --template-file main.bicep \
          --parameters @main.parameters.json

      - name: Output deployment result
        run: |
          echo "Deployment completed successfully."
          az deployment group show --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name main --query properties.outputs -o json
